###
# Test your FastAPI endpoints

POST http://127.0.0.1:1200/products/
Content-Type: application/json

{
  "name": "test_name",
  "volume": "1l",
  "brand": "домик в деревне",
  "category": "food"
}



###
POST http://127.0.0.1:1200/purchases/
Content-Type: application/json

{
  "product_id": 1,
  "price": 200,
  "quantity": 2,
  "tags": ["вредно", "не дома"]
}

###
POST http://195.133.21.239:1200/purchases/
Content-Type: application/json

{
  "product_id": 1,
  "price": 200,
  "quantity": 2,
  "tags": ["вредно", "не дома"]
}

###
POST http://127.0.0.1:1200/checks/
Content-Type: application/json

{
  "purchase_ids": [1, 2, 3]
}

###


GET http://195.133.21.239:1200/products/category/unique
Accept: application/json

###
